//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DharDorkar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Order
    {
        public int OrderId { get; set; }
        public string ProductNames { get; set; }
        public string ProductQuantities { get; set; }
        public Nullable<decimal> TotalPayment { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailId { get; set; }
        public string NationalId { get; set; }
        public string Address { get; set; }
        public Nullable<int> PhoneNumber { get; set; }
    }
}
